"""add facial landmarks and pose fields

Revision ID: 36f2fe28494f
Revises: edfa07214e6c
Create Date: 2026-05-11 13:41:07.403971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f2fe28494f'
down_revision: Union[str, Sequence[str], None] = 'edfa07214e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_faces', sa.Column('landmarks_json', sa.Text(), nullable=True))
    op.add_column('video_faces', sa.Column('smile_score', sa.Float(), nullable=True))
    op.add_column('video_faces', sa.Column('blink_left', sa.Float(), nullable=True))
    op.add_column('video_faces', sa.Column('blink_right', sa.Float(), nullable=True))
    op.add_column('video_faces', sa.Column('brow_raise', sa.Float(), nullable=True))
    op.add_column('video_faces', sa.Column('pitch', sa.Float(), nullable=True))
    op.add_column('video_faces', sa.Column('yaw', sa.Float(), nullable=True))
    op.add_column('video_faces', sa.Column('roll', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_faces', 'roll')
    op.drop_column('video_faces', 'yaw')
    op.drop_column('video_faces', 'pitch')
    op.drop_column('video_faces', 'brow_raise')
    op.drop_column('video_faces', 'blink_right')
    op.drop_column('video_faces', 'blink_left')
    op.drop_column('video_faces', 'smile_score')
    op.drop_column('video_faces', 'landmarks_json')
    # ### end Alembic commands ###
