"""add face index

Revision ID: 59d227fee4fb
Revises: 6945f9d0e968
Create Date: 2026-05-11 14:39:50.885191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d227fee4fb'
down_revision: Union[str, Sequence[str], None] = '6945f9d0e968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_faces', sa.Column('face_index', sa.INTEGER(), nullable=True))
    op.execute('UPDATE video_faces SET face_index = 0 WHERE face_index IS NULL')
    op.alter_column('video_faces', 'face_index', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_faces', 'face_index')
    # ### end Alembic commands ###
